<!--
  <input type="text" title="Zip/Postal Code" name="pickuppoint" id="pickuppoint" value="" class="input-text validate-zip-international  required-entry validation-passed">

<button type="button" title="Continue" class="button" onclick="reloadShipping();"><span><span>SEARCH</span></span></button>
<span id="shipping-refresh-loader" class="please-wait">
  <img src="http://pakettikauppa.local/skin/frontend/rwd/default/images/opc-ajax-loader.gif" alt="Loading next step..." title="Loading next step..." class="v-middle">
   Reloading shipping methods
</span>


<script>


var observeDOM = (function(){
    var MutationObserver = window.MutationObserver || window.WebKitMutationObserver,
        eventListenerSupported = window.addEventListener;
    return function(obj, callback){
        if( MutationObserver ){
            var obs = new MutationObserver(function(mutations, observer){
                if( mutations[0].addedNodes.length || mutations[0].removedNodes.length )
                    callback();
            });
            obs.observe( obj, { childList:true, subtree:true });
        }
        else if( eventListenerSupported ){
            obj.addEventListener('DOMNodeInserted', callback, false);
            obj.addEventListener('DOMNodeRemoved', callback, false);
        }
    };
})();


document.addEventListener('DOMContentLoaded', startObservingDom, false);

function startObservingDom(){

  observeDOM( document.getElementById('checkout-shipping-method-load') ,function(){
      toggleShipping();
  });
}

function toggleShipping(){
    if(jQuery('#shipping-refresh-loader').is(":visible")){
        jQuery("#shipping-refresh-loader").hide();
        jQuery(".sp-methods").show();
    }else{
        jQuery("#shipping-refresh-loader").show();
        jQuery(".sp-methods").hide();
    }
}

function reloadShipping(){
  jQuery(".sp-methods").hide();
  jQuery("#shipping-refresh-loader").show();
  document.getElementById("billing:postcode").value = document.getElementById("pickuppoint").value;
  billing.save();
}
</script> -->
