<input maxlength="10" type="text" placeholder="Post code" title="Postinumero" name="bshipping[postcode2]" id="shipping:postcode2" class="validate-zip-international required-entry input-text">
<a href="#" id="clickme">RELOAD</a>
<script>
  jQuery( "#clickme" ).click(function(e) {
    e.preventDefault();
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_coupon', array('_secure'=>true)); ?>';
    var shipping_methods = $$('dl.shipment-methods').first();
    var payment_methods = $$('div.payment-methods').first();
    var summary = $$('div.onestepcheckout-summary').first();
    shipping_methods.update('<div class="loading-ajax">&nbsp;</div>');
    new Ajax.Request(url, {
        method: 'post',
        parameters: {},
        onSuccess: function(transport) {
            if(transport.status == 200) {

                var response = transport.responseText.evalJSON();

                var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
                var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

                if(shipping_methods){
                    shipping_methods.hide();
                    shipping_methods.update(response.shipping_method);
                    shipping_methods.show();
                    $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
                    $$('dl.shipment-methods input').invoke('observe', 'click', function() {
                        $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                            new Effect.Fade(item);
                        });
                    });
                }

                if(payment_methods){
                    payment_methods.hide();
                    payment_methods.replace(response.payment_method);
                    payment_methods.show();

                    paymentContainer = $('container_payment_method_' + payment.currentMethod)
                    paymentForm = $('payment_form_' + payment.currentMethod)

                    if(paymentContainer != null){
                        paymentContainer.show();
                    }
                    if(paymentForm != null){
                        paymentForm.show();
                    }
                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));
                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function() {
                        $$('div.onestepcheckout-payment-method-error').each(function(item) {
                            new Effect.Fade(item);
                        });
                    });
                }

                summary.hide();
                summary.update(response.summary);
                summary.show();

                if(response.success) {

                    couponNotice.update(response.message);
                    couponNotice.removeClassName('error-msg');
                    couponNotice.addClassName('success-msg');
                    couponNotice.show();
                    /* Show remove button */
                    $('onestepcheckout-coupon-remove').show();
                }
                else    {

                    couponNotice.update(response.message);
                    couponNotice.removeClassName('success-msg');
                    couponNotice.addClassName('error-msg');
                    couponNotice.show();
                    /* Hide remove button */
                    $('onestepcheckout-coupon-remove').hide();
                }
            }
        }
    });
  });
</script>
